### ISSUE TITLE
click not taking 2 arguments

### ISSUE THREAD

**Issue by NathanInbar** [Lonami/autoit#1]
`click(100,100)`

\>>File "\ait\_windows.py", line 534, in click
raise TypeError('0, 1 or 3 arguments required, but {} given'.format(argc))
TypeError: 0, 1 or 3 arguments required, but 2 given

**Comment by Lonami** [comment]
Huh, people use this, nice. Thanks for the report.

**Comment by Lonami** [comment]
Stupid Windows inserting garbage characters in my commit messages.
