### ISSUE TITLE
tooltip not working python 2.7 ?

### ISSUE THREAD

**Issue by BalteMD** [Lonami/autoit#11]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/92046606/218245244-d01bb35a-48e4-47b0-b57d-158dcae199f7.png">

**Comment by Lonami** [comment]
`autoit.tooltip` is not a thing as far as I'm aware (I would be interested to learn where you found that), and the library does not support Python 2 (from the README):

> This Python 3 package aims to [...]
