### ISSUE TITLE
Cannot write in windows

### ISSUE THREAD

**Issue by v-bogucharov** [Lonami/autoit#2]
Hey! I am trying to auto-write the path to select a file in Windows 10 explorer. Some commands from this library work, but text writing does not. I am writing the command ait.write(r'C:\Users\vladconq\ios.csv') and getting this error:
![image](https://user-images.githubusercontent.com/41647156/114690162-1e21a300-9d1f-11eb-917f-55cb0857854d.png)

Can you fix this please?

**Comment by Lonami** [comment]
If you don't care about uppercase, you can use `ait.press(*'Hello ... world!\n')` for the time being.

**Comment by v-bogucharov** [comment]
Thanks for the quick response! I really don't need uppercase now. But all symbols from the path are erased now.

What I trying to do:
![image](https://user-images.githubusercontent.com/41647156/114695761-a5254a00-9d24-11eb-9bc5-5239097b0575.png)

What I get:
![image](https://user-images.githubusercontent.com/41647156/114695823-b2423900-9d24-11eb-8cb1-dd598506ee79.png)

**Comment by Lonami** [comment]
Ah, special symbols also break because they're typed with a key combo. Then this will take a bit more to look into.

**Comment by paololazzari** [comment]
@Lonami Was this ever fixed? I see the same issue that was reported here with the `0.2.4` version:

```python
ait.press(*'C:\\Users')
None
```

will type `cusers`, instead of the desired `c:\users`
