### ISSUE TITLE
grammar issue in description 

### ISSUE THREAD

**Issue by TheAutoMakers** [Lonami/autoit#9]
Hi, sorry to bother with this issue, but i spotted  a grammar error in your PyPi page that lead me here, it said : "How does it look like" and i thought that it sounded weird so i googled and turns out "What does it look like" is the appropriate term. 

Sorry for bothering with this hahaha i just couldn't.

**Comment by Lonami** [comment]
Feel free to send a PR with a fix. I am not a native English speaker, so if the PR would include a pass over the rest of documentation to see if any other sentences need fixing, that would be great.

**Comment by marcelpetrick** [comment]
Hello @TheAutoMakers and @Lonami ,

I've prepared a PR in https://github.com/Lonami/autoit/pull/10
